######################################################################
##
## Filename: test_RISC_SPM.udo
## Created on: Sun Nov 12 13:55:39 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
